image: Visual Studio 2017
platform: Any CPU

environment:
  version: $(APPVEYOR_BUILD_VERSION)

configuration:
- Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%version%'
  package_version: '%version%'
  assembly_version: '%version%'
  file_version: '%version%'
  informational_version: '%version%'

before_build:
  - choco install codecov
  - dotnet tool install --global coverlet.console 
  - dotnet add JsonMasking.Tests/JsonMasking.Tests.csproj package coverlet.msbuild
  - dotnet restore

build:
  project: JsonMasking.sln

test_script:
  # Run test and generate result with opencover format
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=coverage /p:Exclude=[xunit.*]* JsonMasking.sln
  # Send test result to codecov
  - codecov -f .\coverage.opencover.xml -t %CODECOV_TOKEN%

after_test:
  - dotnet pack --configuration Release /p:Version=%version%

artifacts:
  - path: JsonMasking\bin\Release\netstandard2.0\JsonMasking.dll
    name: JsonMasking.dll
  - path: JsonMasking\bin\Release\JsonMasking.%version%.nupkg
    name: JsonMasking.%version%.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: csyDlyeSjDmdYAQ/PK0GYNZ4ofK/yC6vd5ZLPnG2TgujmrAW7fUiQxjDVOWD4XAX